CREATE VIEW [PeopleOnlineToday] AS
SELECT *
FROM Users
WHERE DATEPART(YEAR, LastLogin) = DATEPART(YEAR, GETDATE()) 
	AND DATEPART(MONTH, LastLogin) = DATEPART(MONTH, GETDATE()) 
	AND DATEPART(DAY, LastLogin) = DATEPART(DAY, GETDATE()) 
GO