SELECT CONVERT(NVARCHAR(max), GETDATE(), 104) + ' ' +
		CONVERT(NVARCHAR(max),DATEPART(HOUR, GETDATE())) + ':' +
		CONVERT(NVARCHAR(max),DATEPART(MINUTE, GETDATE())) + ':' +
		CONVERT(NVARCHAR(max),DATEPART(SECOND, GETDATE())) + ':' + 
		CONVERT(NVARCHAR(max),DATEPART(MILLISECOND, GETDATE()))